trunkXOffsetPCoefForward: 0.5
KI_P_qw: 0
KP_4: 0.3
trunkYOnlyInDoubleSupport: false
Gyro_1: 40
trunkPitch: 0.2617994
KD_0: 0.23
Angle_1: 7
trunkHeight: 0.365
KP_1: 0.2
trunkPitchPCoefTurn: 0
Gyro_2: 0
KP_P_qw: 10
Angle_0: 9
KP_0: 0.3
trunkXOffset: 0
footOvershootRatio: 0.05
Gyro_0: 80
KD_P_qw: 5
Angle_4: 10
footApexPhase: 0.5
trunkPitchPCoefForward: 0
Gyro_3: 40
KD_1: 0.18
trunkPause: 0.3
footDistance: 0.18
Angle_3: 8
footOvershootPhase: 0.85
trunkPhase: 0.6
footPutDownPhase: 1
Angle_2: 3
freq: 1.7
trunkYOffset: 0
KD_2: 0
KD_3: 0.19
doubleSupportRatio: 0.045
KD_4: 0.24
Gyro_4: 80
KP_3: 0.1
footPutDownZOffset: 0
setpointPitch: 1
KP_2: 0
trunkXOffsetPCoefTurn: 0
footRise: 0.04
trunkSwing: 0.062